// Declaración de variables para operaciones aritméticas
let a = 15;
let b = 8;

// Realizar operaciones aritméticas básicas
let suma = a + b;
let resta = a - b;
let multiplicacion = a * b;
let division = a / b;

// Mostrar el resultado de cada operación en la consola
console.log("Suma:", suma);
console.log("Resta:", resta);
console.log("Multiplicación:", multiplicacion);
console.log("División:", division);
